name: pyapm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - rdkit
  - openbabel
  - mdanalysis
  - scipy
  - pandas
  - natsort
  - pip
  - pip:
    - -e .